Unhandled exception in thread started by <bound method Thread.__bootstrap of <Thread(/niryo_one/commander/robot_action/result, stopped daemon 140550338483968)>>Unhandled exception in thread started by <bound method Thread.__bootstrap of <Thread(/niryo_one/commander/robot_action/feedback, stopped daemon 140550894561024)>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 814, in __bootstrap_inner
    (self.name, _format_exc()))
  File "/usr/lib/python2.7/traceback.py", line 241, in format_exc
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 814, in __bootstrap_inner
    (self.name, _format_exc()))
  File "/usr/lib/python2.7/traceback.py", line 241, in format_exc
    etype, value, tb = sys.exc_info()
AttributeError: 'NoneType' object has no attribute 'exc_info'
    etype, value, tb = sys.exc_info()
